# Generated by Django 2.2.1 on 2019-06-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.TextField()),
                ('Time', models.DateTimeField()),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('deletion', models.CharField(max_length=1)),
            ],
        ),
    ]
