# Generated by Django 2.2.1 on 2019-06-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deletion',
            field=models.CharField(max_length=10),
        ),
    ]
