# Generated by Django 2.2.1 on 2019-06-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190616_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deletion',
            field=models.BooleanField(default=False),
        ),
    ]
