# Generated by Django 2.2.1 on 2019-06-19 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190616_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('Time', models.DateTimeField()),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('deletion', models.BooleanField(default=False)),
                ('todo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='todo.Todo')),
            ],
        ),
    ]
